# This is a basic workflow that is manually triggered

name: test-tickets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    paths:
      - 'tickets/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
